services:
  _defaults:
    autowire: true

  ICanBoogie\Module\ModuleCollection:
    factory: [ ICanBoogie\Binding\Module\Factory, build_modules ]

  ICanBoogie\Module\ModuleTemplateResolver:
    decorates: ICanBoogie\Render\BasicTemplateResolver
