services:
  _defaults:
    autowire: true

  ICanBoogie\Binding\Module\Config:
    factory: [ '@ICanBoogie\ConfigProvider', config_for_class ]
    arguments:
    - ICanBoogie\Binding\Module\Config

  ICanBoogie\Module\ModuleInstaller:
    class: ICanBoogie\Module\ModuleInstaller\BasicModuleInstaller
    lazy: true

  ICanBoogie\Module\ModuleProvider:
    class: ICanBoogie\Module\ModuleProvider\Container
    arguments:
      $locator: !tagged_locator { tag: module, index_by: id }

  ICanBoogie\Module\ModuleCollection: ~

  # Render

  # The resolver needs to be *after* the basic resolver in the chain,
  # so that module templates may be overwritten
  ICanBoogie\Module\ModuleTemplateResolver:
    tags:
    - { name: render.template_resolver, priority: -10 }

  # Console

  console.command.modules.list:
    class: ICanBoogie\Module\Console\ListModulesCommand
    arguments:
      $style: '%console.style.table%'
    tags:
    - { name: console.command, command: 'modules' }
    - { name: console.command, command: 'modules:list' }
